services:
  - type: web
    name: persona-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/test
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: NODE_ENV
        value: production